// <auto-generated />
using System;
using Logic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Logic.Migrations
{
    [DbContext(typeof(HorrorMovieContext))]
    partial class HorrorMovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Logic.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Logic.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PicturePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Info = "A Phoenix secretary embezzles $40,000 from her employer's client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother. ",
                            Name = "Psycho",
                            PicturePath = "Psycho - Poster.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Info = "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point. ",
                            Name = "Get Out",
                            PicturePath = "Get Out - Poster.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Info = "A family's serene beach vacation turns to chaos when their doppelgängers appear and begin to terrorize them.",
                            Name = "Us",
                            PicturePath = "Us - Poster.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Info = "After a space merchant vessel receives an unknown transmission as a distress call, one of the crew is attacked by a mysterious life form and they soon realize that its life cycle has merely begun. ",
                            Name = "Alien",
                            PicturePath = "Alien - Poster.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Info = "When Cecilia's abusive ex takes his own life and leaves her his fortune, she suspects his death was a hoax. As a series of coincidences turn lethal, Cecilia works to prove that she is being hunted by someone nobody can see. ",
                            Name = "The Invisible Man",
                            PicturePath = "The Invisible Man - Poster.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Info = "In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing. ",
                            Name = "A Quiet Place",
                            PicturePath = "A Quiet Place - Poster.jpg"
                        },
                        new
                        {
                            Id = 7,
                            Info = "When a killer shark unleashes chaos on a beach community, it's up to a local sheriff, a marine biologist, and an old seafarer to hunt the beast down. ",
                            Name = "Jaws",
                            PicturePath = "Jaws - Poster.jpg"
                        },
                        new
                        {
                            Id = 8,
                            Info = "A single mother and her child fall into a deep well of paranoia when an eerie children's book titled Mister Babadook manifests in their home. ",
                            Name = "The Babadook",
                            PicturePath = "The Babadook - Poster.jpg"
                        },
                        new
                        {
                            Id = 9,
                            Info = "A grieving family is haunted by tragic and disturbing occurrences. ",
                            Name = "Hereditary",
                            PicturePath = "Hereditary - Poster.jpg"
                        },
                        new
                        {
                            Id = 10,
                            Info = "Oskar, an overlooked and bullied boy, finds love and revenge through Eli, a beautiful but peculiar girl. ",
                            Name = "Let the right one in",
                            PicturePath = "Let the Right One In - Poster.jpg"
                        });
                });

            modelBuilder.Entity("Logic.Theater", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("GotWheelchairRamp")
                        .HasColumnType("bit");

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("OccupiedSeats")
                        .HasColumnType("int");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Theaters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GotWheelchairRamp = false,
                            MovieId = 1,
                            OccupiedSeats = 0,
                            RoomNumber = 1,
                            StartTime = new DateTime(2021, 6, 22, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 2,
                            GotWheelchairRamp = false,
                            MovieId = 2,
                            OccupiedSeats = 0,
                            RoomNumber = 2,
                            StartTime = new DateTime(2021, 6, 22, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 3,
                            GotWheelchairRamp = false,
                            MovieId = 3,
                            OccupiedSeats = 0,
                            RoomNumber = 3,
                            StartTime = new DateTime(2021, 6, 22, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 4,
                            GotWheelchairRamp = false,
                            MovieId = 4,
                            OccupiedSeats = 0,
                            RoomNumber = 4,
                            StartTime = new DateTime(2021, 6, 22, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 5,
                            GotWheelchairRamp = false,
                            MovieId = 5,
                            OccupiedSeats = 0,
                            RoomNumber = 5,
                            StartTime = new DateTime(2021, 6, 22, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 6,
                            GotWheelchairRamp = false,
                            MovieId = 6,
                            OccupiedSeats = 0,
                            RoomNumber = 6,
                            StartTime = new DateTime(2021, 6, 22, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 7,
                            GotWheelchairRamp = false,
                            MovieId = 7,
                            OccupiedSeats = 0,
                            RoomNumber = 7,
                            StartTime = new DateTime(2021, 6, 22, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 8,
                            GotWheelchairRamp = false,
                            MovieId = 8,
                            OccupiedSeats = 0,
                            RoomNumber = 8,
                            StartTime = new DateTime(2021, 6, 22, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 9,
                            GotWheelchairRamp = true,
                            MovieId = 9,
                            OccupiedSeats = 0,
                            RoomNumber = 9,
                            StartTime = new DateTime(2021, 6, 22, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 10,
                            GotWheelchairRamp = true,
                            MovieId = 10,
                            OccupiedSeats = 0,
                            RoomNumber = 10,
                            StartTime = new DateTime(2021, 6, 22, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 11,
                            GotWheelchairRamp = false,
                            MovieId = 10,
                            OccupiedSeats = 0,
                            RoomNumber = 1,
                            StartTime = new DateTime(2021, 6, 22, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 12,
                            GotWheelchairRamp = false,
                            MovieId = 9,
                            OccupiedSeats = 0,
                            RoomNumber = 2,
                            StartTime = new DateTime(2021, 6, 22, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 13,
                            GotWheelchairRamp = false,
                            MovieId = 8,
                            OccupiedSeats = 0,
                            RoomNumber = 3,
                            StartTime = new DateTime(2021, 6, 22, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 14,
                            GotWheelchairRamp = false,
                            MovieId = 7,
                            OccupiedSeats = 0,
                            RoomNumber = 4,
                            StartTime = new DateTime(2021, 6, 22, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 15,
                            GotWheelchairRamp = false,
                            MovieId = 6,
                            OccupiedSeats = 0,
                            RoomNumber = 5,
                            StartTime = new DateTime(2021, 6, 22, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 16,
                            GotWheelchairRamp = false,
                            MovieId = 5,
                            OccupiedSeats = 0,
                            RoomNumber = 6,
                            StartTime = new DateTime(2021, 6, 22, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 17,
                            GotWheelchairRamp = false,
                            MovieId = 4,
                            OccupiedSeats = 0,
                            RoomNumber = 7,
                            StartTime = new DateTime(2021, 6, 22, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 18,
                            GotWheelchairRamp = false,
                            MovieId = 3,
                            OccupiedSeats = 0,
                            RoomNumber = 8,
                            StartTime = new DateTime(2021, 6, 22, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 19,
                            GotWheelchairRamp = true,
                            MovieId = 2,
                            OccupiedSeats = 0,
                            RoomNumber = 9,
                            StartTime = new DateTime(2021, 6, 22, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 20,
                            GotWheelchairRamp = true,
                            MovieId = 1,
                            OccupiedSeats = 0,
                            RoomNumber = 10,
                            StartTime = new DateTime(2021, 6, 22, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 21,
                            GotWheelchairRamp = false,
                            MovieId = 8,
                            OccupiedSeats = 0,
                            RoomNumber = 1,
                            StartTime = new DateTime(2021, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 22,
                            GotWheelchairRamp = false,
                            MovieId = 7,
                            OccupiedSeats = 0,
                            RoomNumber = 2,
                            StartTime = new DateTime(2021, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 23,
                            GotWheelchairRamp = false,
                            MovieId = 10,
                            OccupiedSeats = 0,
                            RoomNumber = 3,
                            StartTime = new DateTime(2021, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 24,
                            GotWheelchairRamp = false,
                            MovieId = 9,
                            OccupiedSeats = 0,
                            RoomNumber = 4,
                            StartTime = new DateTime(2021, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 25,
                            GotWheelchairRamp = false,
                            MovieId = 6,
                            OccupiedSeats = 0,
                            RoomNumber = 5,
                            StartTime = new DateTime(2021, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 26,
                            GotWheelchairRamp = false,
                            MovieId = 5,
                            OccupiedSeats = 0,
                            RoomNumber = 6,
                            StartTime = new DateTime(2021, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 27,
                            GotWheelchairRamp = false,
                            MovieId = 2,
                            OccupiedSeats = 0,
                            RoomNumber = 7,
                            StartTime = new DateTime(2021, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 28,
                            GotWheelchairRamp = false,
                            MovieId = 1,
                            OccupiedSeats = 0,
                            RoomNumber = 8,
                            StartTime = new DateTime(2021, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 29,
                            GotWheelchairRamp = true,
                            MovieId = 4,
                            OccupiedSeats = 0,
                            RoomNumber = 9,
                            StartTime = new DateTime(2021, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 30,
                            GotWheelchairRamp = true,
                            MovieId = 3,
                            OccupiedSeats = 0,
                            RoomNumber = 10,
                            StartTime = new DateTime(2021, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 31,
                            GotWheelchairRamp = false,
                            MovieId = 3,
                            OccupiedSeats = 0,
                            RoomNumber = 1,
                            StartTime = new DateTime(2021, 6, 23, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 32,
                            GotWheelchairRamp = false,
                            MovieId = 4,
                            OccupiedSeats = 0,
                            RoomNumber = 2,
                            StartTime = new DateTime(2021, 6, 23, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 33,
                            GotWheelchairRamp = false,
                            MovieId = 9,
                            OccupiedSeats = 0,
                            RoomNumber = 3,
                            StartTime = new DateTime(2021, 6, 23, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 34,
                            GotWheelchairRamp = false,
                            MovieId = 2,
                            OccupiedSeats = 0,
                            RoomNumber = 4,
                            StartTime = new DateTime(2021, 6, 23, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 35,
                            GotWheelchairRamp = false,
                            MovieId = 1,
                            OccupiedSeats = 0,
                            RoomNumber = 5,
                            StartTime = new DateTime(2021, 6, 23, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 36,
                            GotWheelchairRamp = false,
                            MovieId = 8,
                            OccupiedSeats = 0,
                            RoomNumber = 6,
                            StartTime = new DateTime(2021, 6, 23, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 37,
                            GotWheelchairRamp = false,
                            MovieId = 7,
                            OccupiedSeats = 0,
                            RoomNumber = 7,
                            StartTime = new DateTime(2021, 6, 23, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 38,
                            GotWheelchairRamp = false,
                            MovieId = 10,
                            OccupiedSeats = 0,
                            RoomNumber = 8,
                            StartTime = new DateTime(2021, 6, 23, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 39,
                            GotWheelchairRamp = true,
                            MovieId = 6,
                            OccupiedSeats = 0,
                            RoomNumber = 9,
                            StartTime = new DateTime(2021, 6, 23, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        },
                        new
                        {
                            Id = 40,
                            GotWheelchairRamp = true,
                            MovieId = 5,
                            OccupiedSeats = 0,
                            RoomNumber = 10,
                            StartTime = new DateTime(2021, 6, 23, 2, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalSeats = 20
                        });
                });

            modelBuilder.Entity("Logic.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("Seat")
                        .HasColumnType("int");

                    b.Property<int>("TheaterId")
                        .HasColumnType("int");

                    b.Property<bool>("Wheelchair")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TheaterId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Logic.Theater", b =>
                {
                    b.HasOne("Logic.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Logic.Ticket", b =>
                {
                    b.HasOne("Logic.Customer", "Customer")
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logic.Theater", "Theater")
                        .WithMany("Tickets")
                        .HasForeignKey("TheaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Theater");
                });

            modelBuilder.Entity("Logic.Customer", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Logic.Theater", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
